#!/bin/bash

#============================================
# General Aliases
#============================================
alias ..='cd ..'
alias ag="ag --path-to-ignore ~/.agignore"
alias c='clear'
alias cd..='cd ..'
alias code='cd ~/Code'
alias dbuild='docker-compose build'
alias ddown='docker-compose down'
alias dup='docker-compose up --remove-orphans'
alias fuck='sudo $(history -p \!\!)'
alias ll='ls -GlahF --color --group-directories-first'
alias ls='gls'
alias ovim='/usr/local/bin/vim'
alias rust-musl-nightly='docker run --rm -it -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder:nightly'
alias serve='python -m SimpleHTTPServer'
alias src='source ~/.zshrc'
alias tmn='tmux attach || tmux -u new -s Tomdizzle'
alias tmux='tmux -u -2'
alias tml='tmux new-session -s Tomdizzle1'
alias tmr='tmux new-session -t Tomdizzle1 -s Tomdizzel2'
alias toml-script='toml_script'
alias v='nvim'
alias vend='cd $SOURCE_DIR'
alias vim='nvim'


#============================================
# Git Aliases
#============================================
alias gita='git add'
alias gitaa='git add -A'
alias gitb="git symbolic-ref HEAD | sed 's!refs\/heads\/!!'"
alias gitc='git commit -m'
alias gitca='git commit --amend'
alias gitcb='git checkout -b'
alias gitd='git diff'
alias gitl='git log --oneline'
alias gitp='git push'
alias gitpb='git push -u origin $(gitb)'
alias gitpl='git pull --rebase'
alias gits='git status -s'


#============================================
# Todoist Aliases
#============================================
alias tda='todoist add'
alias tdai='todoist add -P 178908924'
alias tdl='todoist list'
alias tds='todoist sync'


#============================================
# CLI Augmentations
#============================================

docker() {
  if [[ $1 == "buildx" ]]; then
    command docker build \
      --build-arg http_proxy=${http_proxy} \
      --build-arg https_proxy=${http_proxy} \
      --build-arg no_proxy=${no_proxy} \
      "${@:2}"
  elif [[ $1 == "sh" ]]; then
    docker run -it $2 sh
  else
    command docker "$@"
  fi
}

git() {
  if [[ $1 == "clonem" ]]; then
    command git clone \
      "${MAC_GIT_SSH}$2.git"
  elif [[ $1 == "conf" ]]; then
    command git diff --name-only --diff-filter=U
  else
    command git "$@"
  fi
}

tdaa() {
  tda "$*"
}

#============================================
# Utility Methods
#============================================

# Check if a program exists
program_exists() {
  command -v "$1" >/dev/null 2>&1 ;
}

# Check if a program exists
toml_script() {
  command node -r $HOME/.dotfiles/scripts/global.js $HOME/.dotfiles/scripts/$@
}

