# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

secure_input_notification: false
matches:
  # Simple text replacement
  - trigger: ":jira"
    replace: "https://arlive.atlassian.net/browse/INVFIN-"

  # Dates
  - trigger: ":date:"
    replace: "{{isodate}}"
    vars:
      - name: isodate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":datetime:"
    replace: "{{isodatetime}}"
    vars:
      - name: isodatetime
        type: date
        params:
          format: "%Y-%m-%dT%H:%M:%S"
