[aws]
disabled = false
symbol = "🌥 "

[aws.region_aliases]
ap-southeast-2 = "au"

[custom.toml]
command = "echo 💪"
when = "[[ $(pwd) = ~/Code/toml* ]]"

[custom.work]
command = "echo 🌶"
when = "[[ $(pwd) = ~/Code/work* ]]"

