[aws.region_aliases]
ap-southeast-2 = "au"

[nodejs]
disabled = true

[vagrant]
disabled = true

[lua]
disabled = true

[custom.toml]
command = "echo 💪"
when = "[[ $(pwd) = ~/Code/toml* ]]"

[custom.work]
command = "echo 🦆"
when = "[[ $(pwd) = ~/Code/work* ]]"
