export VIM_COLORSCHEME=dracula

export TMUX_COLOR_BG='#44475a'
export TMUX_COLOR_FG='#6272a4'
export TMUX_COLOR_ACCENT_BG='#bd93f9'
export TMUX_COLOR_ACCENT_FG='#282a36'
export TMUX_COLOR_ACCENT_IDLE_BG='#6e7eaf'
export TMUX_COLOR_ACCENT_IDLE_FG='#333333'
export TMUX_COLOR_HIGHLIGHT_BG='#eeeeee'
export TMUX_COLOR_HIGHLIGHT_FG='#888888'
export TMUX_COLOR_HIGHLIGHT_IDLE_BG='#6e7eaf'
export TMUX_COLOR_HIGHLIGHT_IDLE_FG='#333333'
